apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dotbintask

resources:
- namespace.yaml
- persistentvolumeclaim.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

secretGenerator:
- literals:
  - tokens=dev-token-12345
  name: dotbintask-secret

images:
- name: dotbintask-api
  newName: ghcr.io/dotbinio/dotbintask-api
  newTag: latest
- name: dotbintask-frontend
  newName: ghcr.io/dotbinio/dotbintask-reports-gui
  newTag: latest

labels:
- includeSelectors: true
  pairs:
    app: dotbintask
    app.kubernetes.io/instance: dotbintask
    app.kubernetes.io/name: dotbintask
